export class PgModelConstant {
  public static readonly USER: string = 'users'
  public static readonly USER_SETTING: string = 'user_settings'
  public static readonly USER_POINTS: string = 'user_points'
  public static readonly USER_POINT_HISTORY: string = 'user_point_histories'
  public static readonly FOLLOW: string = 'follows'
  public static readonly POLL: string = 'polls'
  public static readonly POLL_ANSWER: string = 'poll_answers'
  public static readonly POLL_VOTES: string = 'poll_votes'
  public static readonly POLL_COMMENT: string = 'poll_comments'
  public static readonly POLL_CATEGORY_MODEL: string = 'poll_categories'
  public static readonly HIDE_COMMENT: string = 'hide_comments'
  public static readonly USER_DEVICE: string = 'user_device_session'
  public static readonly BLOCK: string = 'blocks'
  public static readonly REPORT_USER: string = 'report_users'
  public static readonly REPORT_POLL: string = 'report_polls'
  public static readonly HASHTAG: string = 'hashtags'
  public static readonly POLL_HASHTAG: string = 'poll_hashtags'
  public static readonly POLL_MENTION: string = 'poll_mentions'
  public static readonly POLL_COMMENT_MENTION: string = 'poll_comment_mentions'
  public static readonly POLL_COMMENT_HASHTAG: string = 'poll_comment_hashtags'
  public static readonly POPULARITY_POLL: string = 'popularity_polls'
  public static readonly POLL_ENTITY: string = 'poll_entities'
  public static readonly SESSION: string = 'sessions'
  public static readonly LIKES: string = 'likes'
  public static readonly GROUP: string = 'groups'
  public static readonly GROUP_SETTINGS: string = 'group_settings'
  public static readonly GROUP_MEMBERS: string = 'group_members'
  public static readonly GROUP_MEMBER_REQUEST: string = 'group_member_requests'
  public static readonly GROUP_MEMBERS_SETTING: string = 'group_member_settings'
  public static readonly GROUP_ACTIVITY: string = 'group_activities'
  public static readonly GLOBAL_POINT: string = 'global_points'
  public static readonly RECOMMEND_CATEGORY_LIST: string =
    'recommended_category_lists'
  public static readonly SEARCH_HISTORY: string = 'search_histories'
  public static readonly CONTACT_LIST: string = 'contact_lists'
  public static readonly USER_LINK_SNS: string = 'user_link_sns'
  public static readonly TRANSACTION: string = 'transactions'
  public static readonly POLL_HANDLE_PRIORITY: string = 'poll_handle_priorities'
  public static readonly POLL_UP_PACKAGE: string = 'poll_up_packages'
  public static readonly POLL_UP_PACKAGE_USER_BOUGHT: string =
    'poll_up_package_user_boughts'
  public static readonly PRIORITY_POLL_BY_DATE: string =
    'priority_poll_by_dates'
}

export default PgModelConstant
