#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

color_echo1 () {
  NO_FORMAT="\033[0m"
  F_BOLD="\033[1m"
  C_WHITE="\033[38;5;15m"
  C_DEEPPINK2="\033[48;5;197m"

  echo "${F_BOLD}${C_WHITE}${C_DEEPPINK2}  $1  ${NO_FORMAT}"

  $1
}

color_echo2 () {
  NO_FORMAT="\033[0m"
  F_BOLD="\033[1m"
  C_WHITE="\033[38;5;15m"
  C_BLUE="\033[48;5;12m"
  
  echo "${F_BOLD}${C_WHITE}${C_BLUE}  $1  ${NO_FORMAT}"

  $1
}


color_echo2 "yarn lint"
color_echo2 "yarn prettier"
color_echo2 "git add ." # re-adds all files that were changed by prettier